export const Actions = {
    UPDATE_USER: "UPDATE_USER",
    UPDATE_TOKEN: "UPDATE_TOKEN",
    UPDATE_TABLE_ID: "UPDATE_TABLE_ID",
    UPDATE_ROOM_ID: "UPDATE_ROOM_ID",
    UPDATE_ORDER: "UPDATE_ORDER",
    UPDATE_RESTRO: "UPDATE_RESTRO",
    CHANGE_THEME: "CHANGE_THEME"
}